name: Test PR

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test PR
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '26'

      - name: Install yarn and dependencies
        run: |
          npm i -g corepack
          corepack enable
          yarn install --immutable

      - name: Run tests
        run: yarn test

      - name: Run lint
        run: yarn lint

      - name: Run build
        run: yarn build
    
  test-deploy-build:
    uses: ./.github/workflows/build-alpine.yaml
